apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: "15.0.0"
      sourceRef:
        kind: HelmRepository
        name: nginx-repo
        namespace: flux-system
  valuesFrom:
    - name: nginx-values
      kind: ConfigMap
