---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 5-demo-helm-release-git-helm-bb-app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: 5-demo-source-git-bb-app
  interval: 30s
  targetNamespace: 5-demo
  valuesFrom:
  - kind: ConfigMap
    name: 5-demo-values
    valuesKey: 5-demo-values.yaml