apiVersion: v1
kind: ConfigMap
metadata:
  name: 5-demo-values
  namespace: flux-system
data:
  5-demo-values.yaml: |-
    replicaCount: 5
    service:
      type: NodePort
      nodePort: 30015
    namespace:
      name: 5-demo
    labels:
      app:
        name: block-buster
        version: 7.6.0
        env: dev
